import type { Problem } from './types';

// This is a partial type because 'id' and 'timestamp' are added dynamically.
type SampleProblem = Omit<Problem, 'id' | 'timestamp' | 'userId'>;

export const sampleProblems: SampleProblem[] = [
  {
    title: "Grid failure in Sector 9",
    category: "Infrastructure",
    location: "Aethelburg",
    severity: "Critical",
    urgency: 9,
    sentimentScore: -0.9,
    keyTrends: ["power grid", "blackout", "cascading failure"],
    summary: "A major power grid failure in Sector 9 has led to a city-wide blackout, causing widespread panic.",
    description: "The primary substation in Sector 9 of Aethelburg suffered a catastrophic failure, leading to a cascading power outage across the entire city. Emergency services are overwhelmed and communication lines are down.",
    date: "2024-07-23",
    archived: false,
  },
  {
    title: "Water Contamination Detected",
    category: "Environment",
    location: "Silver Creek",
    severity: "High",
    urgency: 8,
    sentimentScore: -0.7,
    keyTrends: ["water pollution", "health risk", "industrial waste"],
    summary: "High levels of industrial contaminants have been found in the Silver Creek reservoir, posing a significant health risk.",
    description: "Routine testing of the Silver Creek reservoir revealed dangerous levels of heavy metals, likely from illegal dumping by a nearby industrial complex. Residents are advised to boil all water before use.",
    date: "2024-07-22",
    archived: false,
  },
  {
    title: "Uptick in Cyber Attacks on Banks",
    category: "Cyber Threat",
    location: "Global",
    severity: "High",
    urgency: 7,
    sentimentScore: -0.6,
    keyTrends: ["phishing", "data breach", "financial security"],
    summary: "A coordinated phishing campaign is targeting major financial institutions worldwide, leading to multiple data breaches.",
    description: "A sophisticated hacking group is using advanced phishing techniques to gain access to sensitive customer data from several global banks. Millions of accounts are potentially compromised.",
    date: "2024-07-21",
    archived: false,
  },
  {
    title: "Rise in Youth Unemployment",
    category: "Social Challenge",
    location: "National",
    severity: "Medium",
    urgency: 6,
    sentimentScore: -0.5,
    keyTrends: ["unemployment", "economic downturn", "youth"],
    summary: "National statistics show a sharp increase in unemployment among young adults, raising concerns about long-term economic stability.",
    description: "The latest economic report indicates that youth unemployment has risen by 15% in the last quarter. Experts point to automation and a lack of entry-level positions as primary causes.",
    date: "2024-07-20",
    archived: false,
  },
  {
    title: "Bridge Integrity Compromised",
    category: "Infrastructure",
    location: "Port City",
    severity: "High",
    urgency: 8,
    sentimentScore: -0.8,
    keyTrends: ["structural failure", "public safety", "transportation"],
    summary: "The main bridge in Port City has been closed due to a discovery of critical structural weaknesses.",
    description: "An inspection of the Grand Canal Bridge in Port City has revealed severe corrosion and stress fractures in its main support beams. The bridge has been immediately closed to all traffic to prevent a potential collapse.",
    date: "2024-07-19",
    archived: false,
  },
  {
    title: "Illegal Deforestation in Amazon",
    category: "Environment",
    location: "Amazon Rainforest",
    severity: "High",
    urgency: 7,
    sentimentScore: -0.7,
    keyTrends: ["deforestation", "climate change", "illegal logging"],
    summary: "Satellite imagery shows an alarming increase in illegal deforestation activities in protected areas of the Amazon rainforest.",
    description: "Environmental groups report that large swaths of the Amazon are being cleared for illegal logging and agriculture, threatening biodiversity and accelerating climate change.",
    date: "2024-07-18",
    archived: true,
  },
  {
    title: "Organized Retail Crime Surge",
    category: "Public Safety",
    location: "Various Cities",
    severity: "Medium",
    urgency: 5,
    sentimentScore: -0.4,
    keyTrends: ["theft", "retail", "organized crime"],
    summary: "Retailers are reporting a significant increase in organized smash-and-grab thefts, leading to major losses.",
    description: "Coordinated groups are targeting high-end retail stores in major cities, executing rapid thefts of valuable merchandise. Law enforcement is struggling to keep up with the frequency and scale of the incidents.",
    date: "2024-07-17",
    archived: false,
  },
  {
    title: "Disinformation Campaign on Social Media",
    category: "Cyber Threat",
    location: "Online",
    severity: "Medium",
    urgency: 6,
    sentimentScore: -0.6,
    keyTrends: ["fake news", "social media", "disinformation"],
    summary: "A foreign-backed disinformation campaign is spreading false narratives online to influence public opinion.",
    description: "A network of bots and fake accounts is actively spreading politically motivated disinformation on major social media platforms, aiming to create social discord and mistrust.",
    date: "2024-07-16",
    archived: false,
  },
  {
      title: "Homelessness Crisis Worsens",
      category: "Social Challenge",
      location: "Metropolis",
      severity: "High",
      urgency: 8,
      sentimentScore: -0.8,
      keyTrends: ["homelessness", "housing crisis", "poverty"],
      summary: "The number of people experiencing homelessness in Metropolis has reached a record high amid soaring rent prices.",
      description: "Shelters are at full capacity as a severe housing crisis, coupled with a lack of affordable options, has forced thousands onto the streets of Metropolis. City officials are calling for federal aid.",
      date: "2024-07-15",
      archived: false,
  },
  {
      title: "Frequent Sinkholes Opening Up",
      category: "Infrastructure",
      location: "Limestone County",
      severity: "Medium",
      urgency: 7,
      sentimentScore: -0.6,
      keyTrends: ["sinkhole", "geological instability", "aging pipes"],
      summary: "A series of sinkholes have appeared in Limestone County, swallowing roads and damaging property.",
      description: "Geologists suspect that aging, leaking underground water pipes are eroding the limestone bedrock beneath the county, leading to an increasing number of dangerous sinkholes.",
      date: "2024-07-14",
      archived: false,
  }
];
